# Default template for saidata metadata generation
version: 0.1

packages:
  default:
    name: $software_name
    version: latest
    install_options: ~ # Default is undefined.
  dev:
    name: $software_name-dev
    version: latest
    install_options: ~ # Default is undefined.
  doc:
    name: $software_name-doc
    version: latest
    install_options: ~ # Default is undefined.

services:
  default:
    name: $software_name
    enabled: false
    status: ~

directories:
  config: # Main configuration directory
    path: /etc/$software_name
    owner: root
    group: root
    mode: "0755"
  dotconf: # Dot conf directory, with separated configuration files, if applicable
    path: /etc/$software_name/conf.d
    owner: root
    group: root
    mode: "0755"
  log:
    path: /var/log/$software_name
    owner: root
    group: root
    mode: "0755"
  data: ~ # Main data directory (what you need to backup), default is undefined

processes:
  default: 
    name: $software_name
    command: ~
    args: ~

ports:
  default:
    number: ~
    protocol: tcp
    service: ~

containers:
  upstream:
    name: $software_name
    image: $software_name
    tag: latest

charts: {}

repos: {}

urls:
  website: ~
  sbom: ~
  issues: ~
  documentation: ~
  support: ~
  source: ~
  license: ~
  changelog: ~
  download: ~
  icon: ~

language: ~ # Main programming language

description: ~ # Default is undefined.

category:
  default: ~ # Default is undefined.
  sub: ~ # Default is undefined.
  tags: [] # Default is empty list.

license: ~ # Default is undefined.

platforms: [] # Array of supported platforms, e.g. [linux, windows, macos]