# Nixpkgs base configuration - common settings across all platforms
# Only includes configurations that differ from defaults.yaml
version: 0.1

# Nixpkgs-specific package configuration
packages:
  default:
    name: "{{ software_name }}"
    version: latest

# Nixpkgs-specific URL
urls:
  nixpkgs: "https://search.nixos.org/packages?query={{ software_name }}"