# Helm Linux-specific overrides
version: 0.1

# Linux-specific directory configuration
directories:
  config:
    path: "~/.helm"
    mode: "0755"
  data:
    path: "~/.cache/helm"
    mode: "0755"

# Linux-specific file configuration
files:
  config:
    path: "~/.helm/repositories.yaml"