# Helm Windows-specific overrides
version: 0.1

# Windows-specific directory configuration
directories:
  config:
    path: "%APPDATA%\\helm"
    owner: Administrator
    group: Administrators
    mode: "0644"
  data:
    path: "%LOCALAPPDATA%\\helm"
    owner: Administrator
    group: Administrators
    mode: "0644"

# Windows-specific file configuration
files:
  config:
    path: "%APPDATA%\\helm\\repositories.yaml"
    owner: Administrator
    group: Administrators
    mode: "0644"