# Enterprise Configuration for Saidata Generator
# Production-ready configuration with enhanced features

# Core settings
cache:
  directory: "/var/cache/saidata-gen"
  ttl: 7200  # 2 hour cache TTL for production
  max_size: "10GB"
  cleanup_interval: 3600
  compression: true

# Repository fetcher configuration
fetcher:
  concurrent_requests: 10
  request_timeout: 60
  retry_count: 5
  retry_delay: 2
  rate_limit:
    requests_per_minute: 300
    burst_limit: 50
  enabled_providers:
    - apt
    - dnf
    - yum
    - zypper
    - brew
    - winget
    - scoop
    - choco
    - nuget
    - pypi
    - npm
    - cargo
    - docker
    - helm
    - snap
    - flatpak

# Generation settings
generation:
  output_format: "yaml"
  validate_schema: true
  confidence_threshold: 0.8
  include_dev_packages: true
  parallel_processing: true
  max_workers: 8

# RAG configuration (optional)
rag:
  enabled: false  # Set to true when API keys are configured
  provider: "openai"
  model: "gpt-4"
  temperature: 0.1
  max_tokens: 2000
  fallback_enabled: true

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "/var/log/saidata-gen/saidata-gen.log"
  rotation:
    max_bytes: 10485760  # 10MB
    backup_count: 5

# Security settings
security:
  validate_urls: true
  allowed_domains: []  # Empty means all domains allowed
  blocked_domains:
    - "malicious-site.com"
  ssl_verify: true
  timeout_limits:
    connection: 30
    read: 60

# Performance settings
performance:
  connection_pool_size: 20
  connection_pool_maxsize: 100
  memory_limit: "2GB"
  disk_cache_limit: "5GB"

# Quality settings
quality:
  min_confidence_score: 0.7
  cross_reference_validation: true
  source_attribution: true
  quality_gates:
    min_sources: 2
    required_fields:
      - description
      - license
      - urls.website
    validation_rules:
      - no_empty_descriptions
      - valid_license_format
      - valid_urls

# Template settings
templates:
  use_defaults: true
  custom_templates_dir: "/etc/saidata-gen/templates"
  provider_overrides:
    enterprise:
      priority: 1
      templates:
        - enterprise-defaults.yaml

# Monitoring and metrics
monitoring:
  enabled: true
  metrics_endpoint: "http://localhost:9090/metrics"
  health_check_endpoint: "/health"
  performance_tracking: true