# Composer (PHP) base configuration - common settings across all platforms
# Only includes configurations that differ from defaults.yaml
version: 0.1

# Composer-specific package configuration
packages:
  default:
    name: "{{ software_name }}"
    version: latest
    install_options: ["--global"] # Global installation by default

# Composer-specific URL
urls:
  composer: "https://packagist.org/packages/{{ software_name }}"